#ifndef __KEY_ID_DEFINE_H__
#define __KEY_ID_DEFINE_H__

#define HALTOKEY_GET_KEY				0x00

#define HALTOKEY_KEYVAL_NP				0x00
#define HALTOKEY_KEYVAL_SLEEP			0x01
#define HALTOKEY_KEYVAL_MENU			0x02
#define HALTOKEY_KEYVAL_AV				0x03
#define HALTOKEY_KEYVAL_DVD				0x04
#define HALTOKEY_KEYVAL_CDC				0x05
#define HALTOKEY_KEYVAL_RADIO			0x06
#define HALTOKEY_KEYVAL_IPOD			0x07
#define HALTOKEY_KEYVAL_BT				0x08
#define HALTOKEY_KEYVAL_AC				0x09
#define HALTOKEY_KEYVAL_TV				0x0A
#define HALTOKEY_KEYVAL_FM1				0x0B
#define HALTOKEY_KEYVAL_FM2				0x0C
#define HALTOKEY_KEYVAL_AM				0x0D
#define HALTOKEY_KEYVAL_FM				0x0E

#define HALTOKEY_KEYVAL_NAVI			0x10
#define HALTOKEY_KEYVAL_DEST			0x11
#define HALTOKEY_KEYVAL_LOCAL			0x12
#define HALTOKEY_KEYVAL_SETUP			0x13
#define HALTOKEY_KEYVAL_INFO			0x14
#define HALTOKEY_KEYVAL_AUX				0x15

#define HALTOKEY_KEYVAL_MEDIA			0x17

#define HALTOKEY_KEYVAL_KB_FLY_MENU     0x30
#define HALTOKEY_KEYVAL_CALL			0x31
#define HALTOKEY_KEYVAL_CALL_REJECT		0x32
#define HALTOKEY_KEYVAL_DIMM			0x33
#define HALTOKEY_KEYVAL_OPEN			0x34
#define HALTOKEY_KEYVAL_VOL_INC			0x35
#define HALTOKEY_KEYVAL_VOL_DEC			0x36
#define HALTOKEY_KEYVAL_MUTE			0x37
#define HALTOKEY_KEYVAL_SEEK_INC		0x38
#define HALTOKEY_KEYVAL_SEEK_DEC		0x39
#define HALTOKEY_KEYVAL_TUNE_DOWN		0x3A
#define HALTOKEY_KEYVAL_TUNE_INC		0x3B
#define HALTOKEY_KEYVAL_TUNE_DEC		0x3C
#define HALTOKEY_KEYVAL_SEEK_INC2		0x3D
#define HALTOKEY_KEYVAL_SEEK_DEC2		0x3E
#define HALTOKEY_KEYVAL_PANEL_ANGLE		0x3F
#define HALTOKEY_KEYVAL_PANEL_OPEN		0x40
#define HALTOKEY_KEYVAL_KEY_UP			0x41
#define HALTOKEY_KEYVAL_KEY_DOWN		0x42
#define HALTOKEY_KEYVAL_KEY_LEFT		0x43
#define HALTOKEY_KEYVAL_KEY_RIGHT		0x44
#define HALTOKEY_KEYVAL_KEY_ENTER		0x45
#define HALTOKEY_KEYVAL_kEY_CALLOUT		0x46
#define HALTOKEY_KEYVAL_KEY_CALLINOUT	0x47
#define HALTOKEY_KEYVAL_KEY_SCAN		0x48
#define HALTOKEY_KEYVAL_KEY_PAUSE		0x49
#define HALTOKEY_KEYVAL_KEY_TUNE_DOWN2	0x4A
#define HALTOKEY_KEYVAL_KEY_KB_SCREEN	0x4D
#define KEY_FAST_FORWARD                0x4E
#define KEY_FAST_BACKWARD               0x4F
#define KEY_RELEASE                     0xFF


#define HALTOKEY_KEYVAL_KEY_STT			0x50

#define HALTOKEY_KEYVAL_KEY_DVD_SEEK_INC		0x60
#define HALTOKEY_KEYVAL_KEY_DVD_SEEK_DEC		0x61
#define HALTOKEY_KEYVAL_KEY_RADIO_SEEK_INC		0x62
#define HALTOKEY_KEYVAL_KEY_RADIO_SEEK_DEC		0x63
#define HALTOKEY_KEYVAL_KEY_SRADIO_SEEK_INC		0x64
#define HALTOKEY_KEYVAL_KEY_SRADIO_SEEK_DEC		0x65

#define HALTOKEY_KEYVAL_KEY_CUSTOM_APK_1		0xD1
#define HALTOKEY_KEYVAL_KEY_CUSTOM_APK_2		0xD2
#define HALTOKEY_KEYVAL_KEY_CUSTOM_APK_3		0xD3


#define HALTOKEY_KEYVAL_KEY_HOME					0xF0
#define HALTOKEY_KEYVAL_KEY_MENU					0xF1
#define HALTOKEY_KEYVAL_KEY_BACK					0xF2

#define HALTOKEY_KEYVAL_ANDROIDSPEECH               0xE0
#define HALTOKEY_KEY_DNV_SWITCH_SHORT_PRESS			0xE2
#define HALTOKEY_KEY_DNV_AVOID_GLARE_LONG_PRESS		0xE3

#endif

