#ifndef __OTHER_MODULE_RESPONSE_COMMAND_H__
#define __OTHER_MODULE_RESPONSE_COMMAND_H__

#include "global.h"
#include "flytypes.h"

#define REMOTEONLINE_INFORS_HAND_BRAKE 	0x01
#define REMOTEONLINE_INFORS_MAIN_DRIVER_SEAT_BELT 0x02
#define REMOTEONLINE_INFORS_OIL_CONSUMPTION 0x03
#define REMOTEONLINE_INFORS_TOTAL_MILEAGE 0x04
#define REMOTEONLINE_INFORS_ENGINE_SPEED 0x05
#define REMOTEONLINE_INFORS_INSTANTANOUS_SPEED 0x06
#define REMOTEONLINE_INFORS_WATER_TEMPEATURE 0x07
#define REMOTEONLINE_INFORS_ACCON_BATTERY 0x08
#define REMOTEONLINE_INFORS_DOORS 		0x09
#define REMOTEONLINE_INFORS_ENGINE_DOOR 0x0A
#define REMOTEONLINE_INFORS_FOOT_BRAKE 0x0B
#define REMOTEONLINE_INFORS_STALL     0x0C
#define REMOTEONLINE_INFORS_CLEANING_LIQUID 0x0D
#define REMOTEONLINE_INFORS_RESIDUA_MILEAGE 0x0E
#define REMOTEONLINE_INFORS_AVERAGE_FUEL_CONSUMPTION 0x0F
#define REMOTEONLINE_INFORS_TIRE_PRESSURE_UNIT 0x11
#define REMOTEONLINE_INFORS_TIRE_TEMPEARATURE_UNIT 0x12
#define REMOTEONLINE_INFORS_PRESSURE_TEMPEATATURE_VALUE_FL 0x13
#define REMOTEONLINE_INFORS_PRESSURE_TEMPEATATURE_VALUE_FR 0x14
#define REMOTEONLINE_INFORS_PRESSURE_TEMPEATATURE_VALUE_RL 0x15
#define REMOTEONLINE_INFORS_PRESSURE_TEMPEATATURE_VALUE_RR 0x16
#define REMOTEONLINE_INFORS_BATTERY_ANOMALY_MONITORING 0x17

#define REMOTEONLINE_INFORS_OUTSID_TEMPEATURE 0x40
#define REMOTEONLINE_INFORS_DOOR_LOCKS 	0x41
#define REMOTEONLINE_INFORS_COPILOT_DRIVER_SEAT_BELT 0x42
#define REMOTEONLINE_INFORS_DOOR_WINDOWS 0x43
#define REMOTEONLINE_INFORS_CAR_DORMER   0x44
#define REMOTEONLINE_INFORS_CAR_HEADER_LIGHT 0x45
#define REMOTEONLINE_INFORS_ACCOFF_BATTERY 0x46



void otherModuleInit(void);
void otherModuleDeInit(void);
void analyseOtherModuleMessage(moduleid_t sendModuleId, u8 *param, u8 len);

void ModuleToRemoteOnline_FromExtcarMessage(u8 *p, u8 len);
void MakeToCarMessage();
void AccOffMakeToCarMessage();

void ModuleToRemoteOnline_FromSystemMessage(u8 *p, u8 len);
void ModuleToRemoteOnline_FromCenterMessage(u8 *p, u8 len);

#endif
