/*
	author: YanBin Deng
	  date: 2014/09/01  
*/
#pragma once
//num 
#define	WARN_ITEM_NUM 	2
#define CUR_CLICK_BTN_DEFAULT_VALUE		0xFFFFFFFF
//ctrl status
#define OSD_T123_BTN_STATUS_DOWN	1
#define OSD_T123_BTN_STATUS_UP		0
#define DIRECTION_STATUS_DOWN			1
#define DIRECTION_STATUS_UP				4

#define LCD_CLOSE					0
#define LCD_OPEN					1
#define LCD_OPEN_DEFAULT_TIME		7000 //ms

//page id
#define OSD_T123_PAGE_NONE			0x00
#define OSD_T123_PAGE_VIEW			0x58
#define OSD_T123_PAGE_PLAY			0x59
#define OSD_T123_PAGE_PAUSE			0x5A
#define OSD_T123_PAGE_OTHER_MAIN	0x5D
#define OSD_T123_PAGE_OTHER_COLOR_SETTING	0x5E
//ctrl id
#define VIEW_RECORD_STATUS			0x01
#define VIEW_DAY					0x02
#define VIEW_NIGHT					0x03
#define VIEW_FOG_SEE				0x04
#define VIEW_AVOID_GLARE			0x05
#define VIEW_HUMAN_WARNING			0x06
#define VIEW_ROAD_WARNING		0x07
#define VIEW_TRAFFIC_WARNING	0x08
#define VIEW_TF_CARD				0x09
#define VIEW_PLAYBACK				0x0A
#define VIEW_RECORD					0x0B
#define VIEW_UP						0x0C
#define VIEW_LEFT					0x0D
#define VIEW_RIGHT					0x0E
#define VIEW_DOWN					0x0F
#define VIEW_OK						0x10
#define VIEW_HOME					0x11

#define PAUSE_MENU					0x01
#define PAUSE_VIEW					0x02
#define PAUSE_PRE_FILE				0x03
#define PAUSE_PLAY					0x04
#define PAUSE_NEXT_FILE				0x05
#define PAUSE_HOME					0x06

#define PLAY_MENU					0x01
#define PLAY_VIEW					0x02
#define PLAY_FB						0x03
#define PLAY_PAUSE					0x04
#define PLAY_FF						0x05
#define PLAY_HOME					0x06

#define OTHER_MAIN_SET				0x01
#define OTHER_MAIN_BACK				0x02

#define OTHER_COLOR_SET_BACK				0x00
#define OTHER_COLOR_SET_SATURATION_DOWN		0x01
#define OTHER_COLOR_SET_SATURATION_UP		0x02
#define OTHER_COLOR_SET_BRIGHTNESS_DOWN		0x03
#define OTHER_COLOR_SET_BRIGHTNESS_UP		0x04
#define OTHER_COLOR_SET_COLOR_DOWN			0x05
#define OTHER_COLOR_SET_COLOR_UP			0x06
#define OTHER_COLOR_SET_CONTRAST_DOWN		0x07
#define OTHER_COLOR_SET_CONTRAST_UP			0x08
//timer
#define TIMER_ID_SYNC_TIME_TO_DNV			1
#define TIMER_ID_HIDE_OSD_MENU			2
#define TIMER_ID_AUDIO_WARNING			3
#define TIMER_ID_DNV_PING					4
#define TIMER_ID_HIDE_OTHER_DVR_MENU		5
#define TIMER_ID_HIDE_BLACK_PAGE			6
#define TIMER_ID_CLICK_ENABLE				7
#define TIMER_ID_GO_TO_PLAYBACK				8
#define TIMER_ID_GO_TO_VIEW					9
#define TIMER_ID_OPEN_LCD					10
#define TIMER_ID_OEPN_CAN_SHOW_PLAY_PAUSE	11
#define TIMER_ID_RESET_BUDING_MENU_CLICK		12

#define TIMER_CYCLE_SYNC_TIME_TO_DNV		2000
#define TIMER_CYCLE_HIDE_OSD_MENU		7000
#define TIMER_CYCLE_PING_DNV				5000
#define SYNC_DNV_TIME_CYCLE				120
#define TIMER_CYCLE_HIDE_BLACK_PAGE		7000
#define TIMER_CYCLE_CLICK_ENABLE		2000
#define TIMER_CYCLE_GO_TO_PLAYBACK		100
#define TIMER_CYCLE_GO_TO_VIEW			100

#define TIME_CYCLE_VIEW_TO_PLAYBACK		2000
#define TIME_CYCLE_PLAYBACK_TO_VIEW			2000//1000
#define TIME_CYCLE_VIEW_TO_PLAYBACK_OPEN_LCD		3800
#define TIME_CYCLE_PLAYBACK_TO_VIEW_OPEN_LCD		2000
#define TIME_CYCLE_PLAYBACK_TO_MENU_OPEN_LCD		500
#define TIME_CYCLE_VIDEO_TO_HOME						1500
#define TIME_CYCLE_CAN_SHOW_PLAY_PAUSE					TIME_CYCLE_PLAYBACK_TO_VIEW_OPEN_LCD
#define TIME_CYCLE_RESET_BUDING_MENU_CLICK	1500
//video set

#define VIDEO_SET_SATURATION_UP			0x01
#define VIDEO_SET_SATURATION_DOWN		0x02
#define VIDEO_SET_COLOR_UP				0x03
#define VIDEO_SET_COLOR_DOWN			0x04
#define VIDEO_SET_CONTRAST_UP			0x05
#define VIDEO_SET_CONTRAST_DOWN			0x06
#define VIDEO_SET_BRIGHT_UP				0x07
#define VIDEO_SET_BRIGHT_DOWN			0x08
//////////////////////////////////////////////////////////////////////////
enum E_SETTING_TYPE
{
	SETTING_TYPE_DELETE_CUR_FILE,
	SETTING_TYPE_FORMAT_TF_CARD,
	SETTING_TYPE_UNKNOW
};

enum E_MENU_OP_STATUS
{
       MENU_OP_STATUS_MAIN_MENU,
	MENU_OP_STATUS_BEGIN_FORMAT_TF_CARD,	 
	MENU_OP_STATUS_FORMAT_TF_CARD_FINISH,
	MENU_OP_STATUS_FORMAT_TF_CARD_FAIL,
	MENU_OP_STATUS_BEGIN_DELETE_CUR_FILE,
	MENU_OP_STATUS_DELETE_CUR_FILE_FINISH,
	MENU_OP_STATUS_DELETE_CUR_FILE_FAIL,
	MENU_OP_STATUS_SOFTWARE_VERSION_SHOW,
	MENU_OP_STATUS_TRAFFIC_WARNING_SELECT,
	MENU_OP_STATUS_UNKNOW
};

enum E_DNV_SYSTEM_STATUS
{
	DNV_SYSTEM_STATUS_LOW_POWER_CONSUME,
	DNV_SYSTEM_STATUS_STANDBY, 
	DNV_SYSTEM_STATUS_BACKSTAGE_RECORD, 
	DNV_SYSTEM_STATUS_VIEW,
	DNV_SYSTEM_STATUS_MENU,
	DNV_SYSTEM_STATUS_PLAY,
	DNV_SYSTEM_STATUS_PAUSE,
	DNV_SYSTEM_STATUS_UNKNOW
};

enum E_RECORD_STATUS
{
	RECORD_STATUS_CLOSE,
	RECORD_STATUS_OPEN,
	RECORD_STATUS_UNKNOW
};

enum E_DAY_NIGHT_MODE
{
	DAY_NIGHT_MODE_NIGHT,
	DAY_NIGHT_MODE_DAY,
	DAY_NIGHT_MODE_UNKNOW
};

enum E_FOG_SEE
{
	FOG_SEE_CLOSE,
	FOG_SEE_OPEN,
	FOG_SEE_UNKNOW
};

enum E_AVOID_GLARE
{
	AVOID_GLARE_CLOSE,
	AVOID_GLARE_OPEN,
	AVOID_GLARE_UNKNOW
};

enum E_HUMAN_WARNING
{
	HUMAN_WARNING_CLOSE,
	HUMAN_WARNING_OPEN,
	HUMAN_WARNING_UNKNOW
};

enum E_ROAD_WARNING
{
	ROAD_WARNING_CLOSE,
	ROAD_WARNING_OPEN,
	ROAD_WARNING_UNKNOW
};

enum E_TRAFFIC_WARNING
{
	TRAFFIC_WARNING_CLOSE,
	TRAFFIC_WARNING_OPEN,
	TRAFFIC_WARNING_UNKNOW
};

enum E_TF_CARD
{
	TF_CARD_EXIST,
	TF_CARD_NONE,
	TF_CARD_UNKNOW
};

enum E_WARNING_AUDIO_FILE_ID
{
	WARNING_AUDIO_FILE_ID_HUMAN_IN_THE_FRONT = 100,
	WARNING_AUDIO_FILE_ID_WHEEL_PASS_ROAD_LINE = 101,
	WARNING_AUDIO_FILE_ID_LEFT_WHEEL_PASS_ROAD_LINE,
	WARNING_AUDIO_FILE_ID_RIGHT_WHEEL_PASS_ROAD_LINE,
	WARNING_AUDIO_FILE_ID_UNKNOW
};

enum E_WARN_SCAN_ID
{
	WARN_SCAN_ID_HUMAN_IN_THE_FRONT = 0,
	WARN_SCAN_ID_WHEEL_PASS_ROAD_LINE	= 1
};

struct ST_WARN_ITEM
{
	u8 warnId;
	u32 warnTime; //ms
	bool bNeedWarn;
};


