#ifndef __CAR_INFO_DEFINE_H__
#define __CAR_INFO_DEFINE_H__


#define DEFAULT_OUTDOOR_DEGREE		-10000
#define DEFAULT_NORMAL				-1
#define DEFAULT_STATIC_NORMAL		-20000

enum E_CAR_DOOR{CAR_DOOR_CLOSE, CAR_DOOR_OPEN, CAR_DOOR_UNKNOW};
enum E_HAND_LOCK{HAND_LOCK_UP, HAND_LOCK_DOWN, HAND_LOCK_UNKNOW};
enum E_SAFE_BELT{SAFE_BELT_OPEN, SAFE_BELT_CLOSE, SAFE_BELT_UNKNOW};
enum E_CAR_WINDOW{CAR_WINDOW_CLOSE, CAR_WINDOW_OPEN, CAR_WINDOW_UNKNOW};
enum E_FOOT_LOCK{FOOT_LOCK_OPEN, FOOT_LOCK_CLOSE, FOOT_LOCK_UNKNOW};
enum E_RAIN_WIPER{RAIN_WIPER_OPEN, RAIN_WIPER_CLOSE, RAIN_WIPER_UNKNOW};

#endif

